### ISSUE TITLE
unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST) 

### ISSUE THREAD

**Issue by caominhsg** [sanskritick/indicscript#1]
I had download your source code and run, the debug found  in the file  IndicScript.php 

unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST) 

I am using PHP7

**Comment by vbasky** [comment]
Please provide more information on the error. What were you trying to execute ? And what line number did you get the error.

`unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST)` this is not really helpful

**Comment by caominhsg** [comment]
error code at line 15,
 // Object cache.
    private array $cache = [];

I developed plugin for wordpress, I used 2 files only from your code IndicScript.php and IndicSchemes.php, the file IndicScriptFacade.php and IndicScriptServiceProvider.php not include in code

**Comment by caominhsg** [comment]
Can you review, text convert also incorrect
![image](https://user-images.githubusercontent.com/69635655/100699041-899c5100-33cc-11eb-9af7-fa96ecd01b93.png)

**Comment by vbasky** [comment]
What is the version of PHP you are running on ? Also it would be easier if you can paste the IAST text rather than screenshot

**Comment by caominhsg** [comment]
i'm sorry, I used php version 7.4.9

I had copied IAST text for texting only to make sure it works properly, you can test any IAST text. 

I'm not familiar with Indic script so I had used tool from http://aksharamukha.appspot.com/converter to convert Buddhist script from ISAT to Siddham script and Sanskrit script  

Thank you for your helping

Cao Minh
tangthuphathoc.net

**Comment by caominhsg** [comment]
I attach script for you testing

http://www.dsbcproject.org/canon-text/content/408/1874

Devanāgarī script 
ॐ नमः सर्वज्ञाय॥

एवं मया श्रुतमेकस्मिन् समये भगवान् श्रावस्त्यां विहरति स्म जेतवने अनाथपिण्डदस्यारामे महता भिक्षुसङ्घेन सार्धमर्धत्रयोदशभिभिक्षुसहस्रैः। तद्यथा आयुष्मता चाज्ञातकौण्डिन्येन आयुष्मता च महानाम्ना आयुष्मता च रेवतेन आयुष्मता च वक्कुलेन आयुष्मता च शारिपु[त्रेणा आयुष्मता च] पूर्णेन मैत्रायणी[पुत्रेण] च श्रावकनियुतैः। ते सर्वे येन भगवान् येन च जेतवनं विहारं तेनोपसंक्रान्ता भगवतः पादौ शिरसाभिवन्द्य भगवतः पुरतस्तस्थुर्द्वात्रिंशता बोधिसत्त्वसहस्रैः। तद्यथा सहचित्तोत्पादधर्मचक्रप्रवर्तनेन च बोधिसत्त्वेन महासत्त्वेन अनिक्षिप्तधुरेण च बोधिसत्त्वेन महासत्त्वेन मैत्रेयेण च बोधिसत्त्वेन महासत्त्वेन अवलोकितेश्वरेण च बोधिसत्त्वेन महासत्त्वेन महास्थामप्राप्तेन च बोधिसत्त्वेन महासत्त्वेन। एवंप्रमुखार्द्वात्रिंशता बोधिसत्त्वसहस्रैः। ते सर्वे येन भगवान् येन च जेतवनं विहारं तेनोपसंक्रान्ता भगवतः पादौ शिरसाभिवन्द्य भगवतः पुरतस्तस्थुः। अथ खलु भगवान् पूर्वाण्हकालसमये निवास्य पात्रचीवरमा[त्रः] श्रावस्तीं महानगरीं पिण्डाय प्राविशत्। अथ भगवानायुष्मन्तमा नन्दमामन्त्रयते स्म। गच्छानन्द पात्रं चक्रिकं शिक्यमानय। अथायुष्मानानन्दो भगवतः श्रुतमात्रेण पात्रं चक्रिकं शिक्यं भगवते उपनामयामास। अथायुष्मानान्दो भगवतः कृताञ्जलिपुटो भगवन्तं गाथाभिरध्यभाषत।

Roman IAST Script
oṃ namaḥ sarvajñāya..

evaṃ mayā śrutamekasmin samaye bhagavān śrāvastyāṃ viharati sma jetavane anāthapiṇḍadasyārāme mahatā bhikṣusaṅghena sārdhamardhatrayodaśabhibhikṣusahasraiḥ. tadyathā āyuṣmatā cājñātakauṇḍinyena āyuṣmatā ca mahānāmnā āyuṣmatā ca revatena āyuṣmatā ca vakkulena āyuṣmatā ca śāripu[treṇā āyuṣmatā ca] pūrṇena maitrāyaṇī[putreṇa] ca śrāvakaniyutaiḥ. te sarve yena bhagavān yena ca jetavanaṃ vihāraṃ tenopasaṃkrāntā bhagavataḥ pādau śirasābhivandya bhagavataḥ puratastasthurdvātriṃśatā bodhisattvasahasraiḥ. tadyathā sahacittotpādadharmacakrapravartanena ca bodhisattvena mahāsattvena anikṣiptadhureṇa ca bodhisattvena mahāsattvena maitreyeṇa ca bodhisattvena mahāsattvena avalokiteśvareṇa ca bodhisattvena mahāsattvena mahāsthāmaprāptena ca bodhisattvena mahāsattvena. evaṃpramukhārdvātriṃśatā bodhisattvasahasraiḥ. te sarve yena bhagavān yena ca jetavanaṃ vihāraṃ tenopasaṃkrāntā bhagavataḥ pādau śirasābhivandya bhagavataḥ puratastasthuḥ. atha khalu bhagavān pūrvāṇhakālasamaye nivāsya pātracīvaramā[traḥ] śrāvastīṃ mahānagarīṃ piṇḍāya prāviśat. atha bhagavānāyuṣmantamā nandamāmantrayate sma. gacchānanda pātraṃ cakrikaṃ śikyamānaya. athāyuṣmānānando bhagavataḥ śrutamātreṇa pātraṃ cakrikaṃ śikyaṃ bhagavate upanāmayāmāsa. athāyuṣmānāndo bhagavataḥ kṛtāñjalipuṭo bhagavantaṃ gāthābhiradhyabhāṣata.

**Comment by vbasky** [comment]
I am unable to re-produce it. The Devanagari to IAST conversion works as expected on PHP 7.4 environment. Please make sure the server where the code is running is running the appropriate version. 

Tested both the Laravel Facades as well the non-facades version of the package.

**Comment by caominhsg** [comment]
thanks for your help, I will find out problems for that module, i had move out all constant and use only script transliteration is fine but when use all structure files that you made is broken and it shows error unexpected 'array'...

**Comment by vbasky** [comment]
Please raise a issue when you have all the details of the issue and when it can be reproduced consistently. Closing this for now
